### ISSUE TITLE
arabic localization 

### ISSUE THREAD

**Issue by SamadDev** [ahmedoid/hijri_date#21]
please provide an Arabic name with Arabic text, not an English

**Comment by aarif** [comment]
Try this:

`HijriCalendar.setLocal('ar');`

**Comment by SamadDev** [comment]
thank you for that just one more problem no matter what language the month-day number just has one unknow format and can not style and change the number language

**Comment by aarif** [comment]
Please provide more details of your problem.
- What are you trying to achieve?
- What are you seeing instead?
- What have you tried?

Also, please feel free to make changes to the code and submit pull requests.

**Comment by SamadDev** [comment]
just i would like to show Hijri date with my style format of number and localizate

**Comment by aarif** [comment]
Your request is still not clear.  Have you tried this?

var cal = HijriCalendar.now();
print(cal.toFormat("mm dd yy")); //09 14 39

**Comment by SamadDev** [comment]
<img width="406" alt="Screenshot 2023-02-25 at 11 54 26 AM" src="https://user-images.githubusercontent.com/53392565/221348336-d041c37b-146e-4883-bb28-3f178becec88.png">

![photo5462885632859817171](https://user-images.githubusercontent.com/53392565/221348423-148820b8-f419-4a03-bff6-85eab1194cee.jpg)
 
no matter what I tried the month number style did not change stay like that

**Comment by aarif** [comment]
Sorry my friend.  Your issue is with a different project.

[https://github.com/ahmedoid/hijri_picker](https://github.com/ahmedoid/hijri_picker)
