### ISSUE TITLE
hijri month name print spam

### ISSUE THREAD

**Issue by mamedshahmaliyev** [ahmedoid/hijri_date#3]
After installing the latest version, the long hijri month name is continuously printing to console, please resolve the issue, the problem seems to be related with line   198   print(longMonthName); in umm_alqura_calendar.dart, but i maybe wrong. 

Thanks for great package.

**Comment by ahmedoid** [comment]
WIP...
Thank you for feedback

**Comment by ahmedoid** [comment]
Fixed.

**Comment by mamedshahmaliyev** [comment]
Thanks for prompt resolution. May Allah reward your work.
